package MAR15.ABSTRACTION;

public class ABSTRACTION {

    ///  ABSTRACTION
    /*
     showing only essential details...

1. ABSTRACT CLASS ==> 0-100%
2. INTERFACES ======> 100%

     */

    /// ABSTRACT CLASS======> DECLARED AS ABSTRACT CLASS ====> HAVE TO ADD WORD (ABSTRACT )IN CLASS
    ///  NOTE ====> IF ADDED ABSTRACT METHOD THEN CLASS SHOULD BE ABSTRACT CLASS
}
